---
- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Create log file
    file:
      path: /home/cdduser/mylogfile.log
      state: touch
