---
- name: This is a hello-world example
  hosts: tamme01-L27871
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      file:
        path: /tmp/hw.txt
        state: touch
        mode: u=rw,g=r,o=r
